// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnEEhI_yrVytzKng9NHB7almBOT013cio',
    appId: '1:1026193018136:web:297b0c6577caeabe0da26d',
    messagingSenderId: '1026193018136',
    projectId: 'matchmeow-aebe7',
    authDomain: 'matchmeow-aebe7.firebaseapp.com',
    databaseURL:
        'https://matchmeow-aebe7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matchmeow-aebe7.appspot.com',
    measurementId: 'G-YNVYSR3ZM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFieLXQuSU6hzPa5CVItA3lZgjYZP-2m8',
    appId: '1:1026193018136:android:cc4034deeffcdcae0da26d',
    messagingSenderId: '1026193018136',
    projectId: 'matchmeow-aebe7',
    databaseURL:
        'https://matchmeow-aebe7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matchmeow-aebe7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdFMDc7RcDVufQAPHi9fsbNAFB20YPUdY',
    appId: '1:1026193018136:ios:a1b6c316701d5cdb0da26d',
    messagingSenderId: '1026193018136',
    projectId: 'matchmeow-aebe7',
    databaseURL:
        'https://matchmeow-aebe7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matchmeow-aebe7.appspot.com',
    iosBundleId: 'com.example.proje1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdFMDc7RcDVufQAPHi9fsbNAFB20YPUdY',
    appId: '1:1026193018136:ios:856ccd0bd7249c390da26d',
    messagingSenderId: '1026193018136',
    projectId: 'matchmeow-aebe7',
    databaseURL:
        'https://matchmeow-aebe7-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'matchmeow-aebe7.appspot.com',
    iosBundleId: 'com.example.proje1.RunnerTests',
  );
}
